// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/11/2025, 4:16:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/HP/Documents/thesis.pananaroon/pananaroon/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/plugins/**/*.{js,ts,mjs}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/composables/**/*.{js,ts,mjs}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/utils/**/*.{js,ts,mjs}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Documents/thesis.pananaroon/pananaroon/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;